FROM prowlercloud/prowler:stable
USER root
RUN mkdir -p /var/lib/apt/lists/partial \
 && apt-get update \
 && apt-get install -y curl ca-certificates gnupg lsb-release \
 && curl -sL https://aka.ms/InstallAzureCLIDeb | bash \
 && az version \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
